# Generated by Django 4.2.11 on 2024-03-20 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='article-image'),
        ),
    ]
