# Generated by Django 4.2.11 on 2024-03-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_poll_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
