# Generated by Django 4.2.11 on 2024-03-21 18:58

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_author_delete_quillpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
