# Generated by Django 4.2.11 on 2024-03-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created', '-updated'), 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/article_images/defaultimage.jpg', null=True, upload_to='article_images'),
        ),
    ]
