# Generated by Django 4.2.11 on 2024-03-19 01:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comments_options_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=blog.models.Default_Image, null=True, upload_to='article_images'),
        ),
    ]
