# Generated by Django 4.2.11 on 2024-03-19 23:06

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_quillpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('film', 'Film'), ('books', 'Books')], default='gaming', max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', django_quill.fields.QuillField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=10)),
                ('article_image_url', models.URLField()),
                ('article_image', models.ImageField(default=blog.models.Default_Image, null=True, upload_to='article_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
